Added TLS options for MQTT Server

diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
@@ -432,8 +432,8 @@ if [[ "$USE_MQTT" == "true" ]]; then
 	bashio::log.info "Dynu Updater Initialisation - Testing MQTT connection to $MQTT_HOST"
 	TEST_TOPIC="dynu_updater/selftest"
     TEST_PAYLOAD="selftest_$(date +%s)"
-	if ! OUTPUT=$(timeout 5s mosquitto_pub \
-        -h "$MQTT_HOST" \
+	OUTPUT=$(timeout 5s mosquitto_pub \
+		-h "$MQTT_HOST" \
         -u "$MQTT_USER" \
         -P "$MQTT_PASSWORD" \
         -p "$MQTT_PORT" \
@@ -441,26 +441,27 @@ if [[ "$USE_MQTT" == "true" ]]; then
         -m "$TEST_PAYLOAD" \
         -q 1 \
 		"${TLS_FLAGS[@]}" \
-		2>&1); then
-		
-		bashio::log.warning "Return code = $?"
-		if [ $? -eq 124 ]; then
-			bashio::log.error "Dynu Updater Initialisation - Unable to connect to $MQTT_HOST: Connection timed out after 5 seconds."
-		else
-			bashio::log.error "Dynu Updater Initialisation - Unable to connect to $MQTT_HOST: $OUTPUT"
-			if [[ "$MQTT_USE_TLS" == "true" ]]; then
-				if ! TLS_OUTPUT=$(timeout 5s openssl s_client -connect "${MQTT_HOST}:${MQTT_PORT}" \
-					  -servername "${MQTT_HOST}" \
-					  "${OPENSSL_FLAGS[@]}" \
-					  -verify 10 -verify_return_error < /dev/null 2>&1); then
-					if [ ! $? -eq 124 ]; then
-						REASON=$(echo "$TLS_OUTPUT" | grep -E "verify error|Verify return code|Hostname mismatch|expired|unable|self signed" | head -n 1)
-						bashio::log.error "TLS validation failed: $REASON"
-					fi
-				fi
+		2>&1);
+    EXIT_CODE=$?
+	
+	if [[ $EXIT_CODE -eq 124 ]]; then
+		bashio::log.error "Dynu Updater Initialisation - Unable to connect to $MQTT_HOST: Connection timed out after 5 seconds."
+		exit 1
+	elif [[ $EXIT_CODE -ne 0 ]]; then
+		bashio::log.error "Dynu Updater Initialisation - Unable to connect to $MQTT_HOST: $OUTPUT"
+		if [[ "$MQTT_USE_TLS" == "true" ]]; then
+			TLS_OUTPUT=$(timeout 5s openssl s_client -connect "${MQTT_HOST}:${MQTT_PORT}" \
+				-servername "${MQTT_HOST}" \
+				"${OPENSSL_FLAGS[@]}" \
+				-verify 10 -verify_return_error < /dev/null 2>&1)
+			EXIT_CODE=$?
+			if [ $? -eq 124 ]; then
+				bashio::log.error "Dynu Updater Initialisation - Openssl query failed: Connection timed out after 5 seconds."
+			elif [[ $EXIT_CODE -ne 0 ]]; then
+				REASON=$(echo "$TLS_OUTPUT" | grep -E "verify error|Verify return code|Hostname mismatch|expired|unable|self signed" | head -n 1)
+				bashio::log.error "Dynu Updater Initialisation - Openssl query returned: $REASON"
 			fi
 		fi
-
 		exit 1
 	else
 		bashio::log.info "Dynu Updater Initialisation - Connected to $MQTT_HOST"
@@ -621,3 +622,5 @@ jq -n \
 sleep 1
 
 bashio::log.info "Dynu Updater Initialisation - Complete"
+
+exit 0
