Added TLS options for MQTT Server

diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
@@ -446,12 +446,14 @@ if [[ "$USE_MQTT" == "true" ]]; then
 
 		bashio::log.error "Dynu Updater Initialisation - Unable to connect to $MQTT_HOST. $OUTPUT"
 		
-		
-		if ! openssl s_client -connect "${MQTT_HOST}:${MQTT_PORT}" \
-			  -servername "${MQTT_HOST}" \
-			  "${OPENSSL_FLAGS[@]}" \
-			  -verify 10 -verify_return_error; then
-			bashio::log.error "Dynu Updater Initialisation - Unable to verify failure with openssl"
+		if [[ "$MQTT_USE_TLS" == "true" ]]; then
+			if ! TLS_OUTPUT=$(openssl s_client -connect "${MQTT_HOST}:${MQTT_PORT}" \
+				  -servername "${MQTT_HOST}" \
+				  "${OPENSSL_FLAGS[@]}" \
+				  -verify 10 -verify_return_error < /dev/null 2>&1); then
+				REASON=$(echo "$TLS_OUTPUT" | grep -E "verify error|Verify return code|Hostname mismatch|expired|unable|self signed" | head -n 1)
+				bashio::log.error "TLS validation failed: $REASON"
+			fi
 		fi
 
 		exit 1
