Adding HTTP Status code to Dynu Responses

diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
@@ -136,6 +136,118 @@ if [[ "$CERT_VALID" == "true" ]]; then
 	fi
 fi
 
+bashio::log.info "Dynu Updater Initialisation - Contacting Dynu API"
+
+if DYNU_API_RESPONSE=$(curl -s --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.dynu.com/v2/dns" 2>/dev/null); then
+	HTTP_STATUS=$(jq -r '.statusCode // empty' <<< "$DYNU_API_RESPONSE")
+	
+	if [[ -z "$HTTP_STATUS" ]]; then
+		bashio::log.error "Dynu DNS Initialisation - Invalid or empty JSON returned from Dynu Domain API"
+		exit 1
+	fi
+	
+	EXCEPTION_TYPE=$(jq -r '.exception.type // empty' <<< "$DYNU_API_RESPONSE")
+	
+	EXCEPTION_MESSAGE=$(jq -r '.exception.message // empty' <<< "$DYNU_API_RESPONSE")
+
+	case "$HTTP_STATUS" in
+		200)
+			bashio::log.info "Dynu DNS Initialisation - Dynu Domain API data retrieved."
+			;;
+		*)
+			bashio::log.error "Dynu DNS Initialisation - Dynu Domain API Error: status: $HTTP_STATUS, type: $EXCEPTION_TYPE, message: $EXCEPTION_MESSAGE"
+			exit 1
+			;;
+
+	esac
+else
+	bashio::log.error "Dynu DNS Initialisation - Dynu Domain API could not be loaded"
+	exit 1
+fi
+
+# Retrieve Domain ID
+DYNU_DOMAIN_ID=$(
+	jq -r --arg HOST "$DYNU_HOSTNAME" '
+		.domains[]
+		| select(.name == $HOST)
+		| .id // empty
+	' <<< "$DYNU_API_RESPONSE")
+
+if [[ -z "$DYNU_DOMAIN_ID" ]]; then
+	bashio::log.error "Dynu DNS Initialisation - '$DYNU_HOSTNAME' not found in the Dynu Domain API response"
+	exit 1
+fi
+
+# Retrieve IPv6 enabled status for domain
+DYNU_IPV6_ENABLED=$(jq -r --arg HOST "$DYNU_HOSTNAME" '
+	.domains[]
+	| select(.name == $HOST)
+	| .ipv6 // "false"
+' <<<"$DYNU_API_RESPONSE")
+
+if [[ "$DYNU_IPV6_ENABLED" == "true" ]]; then
+	bashio::log.info "Dynu DNS Initialisation - IPv6 enabled for $DYNU_HOSTNAME."
+fi
+
+if DYNU_RECORDS=$(curl -s --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.dynu.com/v2/dns/${DYNU_DOMAIN_ID}/record" 2>/dev/null); then
+	HTTP_STATUS=$(
+	jq -r '.statusCode // empty' <<< "$DYNU_RECORDS")
+	
+	if [[ -z "$HTTP_STATUS" ]]; then
+		bashio::log.error "Dynu DNS Initialisation - Invalid or empty JSON returned from Dynu Records API"
+		exit 1
+	fi
+	
+	EXCEPTION_TYPE=$(
+	jq -r '.exception.type // empty' <<< "$DYNU_RECORDS")
+	
+	EXCEPTION_MESSAGE=$(
+	jq -r '.exception.message // empty' <<< "$DYNU_RECORDS")
+
+	case "$HTTP_STATUS" in
+		200)
+			bashio::log.info "Dynu DNS Initialisation - Dynu Records API data retrieved."
+			;;
+		*)
+			bashio::log.error "Dynu DNS Initialisation - Dynu Records API Error: status: $HTTP_STATUS, type: $EXCEPTION_TYPE, message: $EXCEPTION_MESSAGE"
+			exit 1
+			;;
+
+	esac
+else
+	bashio::log.error "Dynu DNS Initialisation - Dynu Records API could not be loaded"
+	exit 1
+fi
+
+readarray -t DYNU_HOSTNAMES < <(
+  jq -r '
+	[.dnsRecords[]
+	  | select(.recordType | IN("SOA","A","AAAA"))
+	  | .hostname
+	]
+	| unique
+	| sort_by( (split(".") | length), . )
+	| .[]
+  ' <<< "$DYNU_RECORDS"
+)
+
+if [[ ${#DYNU_HOSTNAMES[@]} -eq 0 ]]; then
+	bashio::log.error "Dynu DNS Initialisation - no valid hostnames returned by Dynu Records API"
+	exit 1
+fi
+
+jq -n \
+  --arg ipv6 "$DYNU_IPV6_ENABLED" \
+  --argjson domains "$(printf '%s\n' "${DYNU_HOSTNAMES[@]}" | jq -R . | jq -s .)" \
+  '{
+      ipv6: $ipv6,
+      domains: $domains
+   }' \
+  > /run/dynu-domain_data.conf
+  
+# printf "%s\n" "${DOMAIN_ARR[@]}" > /run/dynu_domain_data.conf
+	
+bashio::log.info "Dynu Updater Initialisation - Generating MQTT Configuration"
 # MQTT connection
 
 MQTT_HOST=""
