Added HA events

diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run
@@ -94,15 +94,15 @@ mqtt_publish() {
 }
 
 fire_event() {
-    if ! RESPONSE=$(curl -s --max-time 5 -X POST \
+    if ! curl -s --fail --max-time 5 -X POST \
       -H "Authorization: Bearer $HASSIO_TOKEN" \
       -H "Content-Type: application/json" \
       -d "$1" \
-      "http://hassio/homeassistant/api/events/dynu_updater" >/dev/null); then
+      "http://hassio/homeassistant/api/events/dynu_updater" >/dev/null; then
 	  
-		bashio::log.error "Dynu IP Updater - Could not send ${1} to Home Assistant Events"
+		bashio::log.error "Dynu IP Updater - Could not send ${1} to Home Assistant Events."
 	else
-		bashio::log.debug "Dynu IP Updater - Sent ${1} to Home Assistant Events. Response: ${RESPONSE}"
+		bashio::log.debug "Dynu IP Updater - Sent ${1} to Home Assistant Events."
 	fi
 }
 
@@ -177,7 +177,7 @@ renew_cert() {
 	if [[ "$CERTBOT_EXIT" -ne 0 ]]; then
 		bashio::log.error "Certificate Manager - Certbot failed with code ${CERTBOT_EXIT}."
 		LAST_CHECK="error"
-		fire_event '{"type": "certificate", "action": "certificate_opdate", "status": "fail"}'
+		fire_event '{"action": "certificate_update", "status": "fail"}'
 	else
 		# If certbot succeeded, check if certificate was updated
 		# Load output into a variable
@@ -190,15 +190,15 @@ renew_cert() {
 			cp "${CERT_PATH}/privkey.pem" "/ssl/$KEYFILE"
 			cp "${CERT_PATH}/fullchain.pem" "/ssl/$CERTFILE"
 			bashio::log.info "Certificate Manager - New certificates copied to /ssl."
-			fire_event '{"type": "certificate", "action": "certificate_opdate", "status": "success"}'
+			fire_event '{"action": "certificate_update", "status": "updated"}'
 		elif echo "$CERTBOT_OUTPUT" | grep -q "Certificate not yet due for renewal"; then
 			bashio::log.info "Certificate Manager - Current certificate is valid."
-			fire_event '{"type": "certificate", "action": "certificate_opdate", "status": "no_change"}'
+			fire_event '{"action": "certificate_update", "status": "no_change"}'
 		elif [[ "$DRY_RUN" == "true" ]] && echo "$CERTBOT_OUTPUT" | grep -q "The dry run was successful"; then	
 			bashio::log.info "Certificate Manager - The dry-run was successful."
 		else
 			bashio::log.warning "Certificate Manager - Unexpected Certbot output"
-			fire_event '{"type": "certificate", "action": "certificate_opdate", "status": "fail"}'
+			fire_event '{"action": "certificate_update", "status": "fail"}'
 		fi
 	fi
 }
@@ -249,7 +249,7 @@ check_cert_dates() {
 		
         # If parsing fails, force renewal
         if [[ -n "$VALID_FROM_RAW" && -n "$CREATED_RAW" && -n "$EXPIRY_RAW" && "${#CERT_DOMAINS[@]}" -ne 0 ]]; then
-			fire_event '{"type": "certificate", "action": "certificate_check", "status": "success"}'
+			fire_event '{"action": "certificate_check", "status": "ok"}'
 			VALID_FROM_ISO=$(date -u -d "${VALID_FROM_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
 			CREATED_ISO=$(date -u -d "${CREATED_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
 			EXPIRY_ISO=$(date -u -d "${EXPIRY_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
@@ -333,7 +333,7 @@ check_cert_dates() {
 		else
 			bashio::log.warning "Certificate Manager - Unable to parse current certificate data."
             mqtt_publish "last_cert_status" "false"
-			fire_event '{"type": "certificate", "action": "certificate_check", "status": "fail"}'
+			fire_event '{"certificate_check", "status": "fail"}'
             renew_cert
         fi
     else
@@ -360,7 +360,7 @@ check_cert_dates() {
 			fi
 
             if [[ -n "$VALID_FROM_RAW" && -n "$CREATED_RAW" && -n "$EXPIRY_RAW" ]]; then
-				fire_event '{"type": "certificate", "action": "certificate_check", "status": "success"}'
+				fire_event '{"action": "certificate_check", "status": "ok"}'
 				VALID_FROM_ISO=$(date -u -d "${VALID_FROM_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
 				CREATED_ISO=$(date -u -d "${CREATED_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
 				EXPIRY_ISO=$(date -u -d "${EXPIRY_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
@@ -385,13 +385,13 @@ check_cert_dates() {
                 bashio::log.warning "Certificate Manager - Unable to parse renewed certificate dates. Recheking in 10 minutes"
                 mqtt_publish "last_cert_status" "false"
 				NEXT_CHECK=$(( NOW_EPOCH + 600 ))
-				fire_event '{"type": "certificate", "action": "certificate_check", "status": "fail"}'
+				fire_event '{"action": "certificate_check", "status": "fail"}'
             fi
         else
             bashio::log.warning "Certificate Manager - Certificate missing/not created after renewal. Check the logs for more information. Recheking in 10 minutes"
             mqtt_publish "last_cert_status" "false"
 			NEXT_CHECK=$(( NOW_EPOCH + 600 ))
-			fire_event '{"type": "certificate", "action": "certificate_check", "status": "fail"}'
+			fire_event '{"action": "certificate_check", "status": "fail"}'
         fi
     fi
 }
diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
@@ -76,15 +76,15 @@ mqtt_publish() {
 }
 
 fire_event() {
-    if ! RESPONSE=$(curl -s --max-time 5 -X POST \
+    if ! curl -s --fail --max-time 5 -X POST \
       -H "Authorization: Bearer $HASSIO_TOKEN" \
       -H "Content-Type: application/json" \
       -d "$1" \
-      "http://hassio/homeassistant/api/events/dynu_updater" >/dev/null); then
+      "http://hassio/homeassistant/api/events/dynu_updater" >/dev/null; then
 	  
-		bashio::log.error "Dynu IP Updater - Could not send ${1} to Home Assistant Events"
+		bashio::log.error "Dynu IP Updater - Could not send ${1} to Home Assistant Events."
 	else
-		bashio::log.debug "Dynu IP Updater - Sent ${1} to Home Assistant Events. Response: ${RESPONSE}"
+		bashio::log.debug "Dynu IP Updater - Sent ${1} to Home Assistant Events."
 	fi
 }
 
@@ -229,7 +229,7 @@ check_ip_status() {
 	if [[ ${#IPV4_DOMAIN_ARR[@]} -eq 0 || -n "$IPV4" ]] && [[ ${#IPV6_DOMAIN_ARR[@]} -eq 0 || -n "$IPV6" ]]; then
 		mqtt_publish "wan_connection" "true"
 		mqtt_publish "last_ip_check" "$(date -Is)"
-		fire_event '{"type": "ip", "action": "ip_check", "status": "success"}'
+		fire_event '{"action": "ip_check", "status": "ok", "data": {"ipv4": "${IPV4}", "ipv6": "${IPV6}"}}'
 		
 		if [[ "$LAST_CHECK" == "false" || "$IPV4" != "$CURRENT_IPV4" || "$IPV6" != "$CURRENT_IPV6" ]]; then
 			if [[ "$LAST_CHECK" == "false" ]]; then
@@ -267,7 +267,7 @@ check_ip_status() {
 				mqtt_publish "update_status" "false"
 				NOW_EPOCH=$(date +%s)
 				NEXT_CHECK=$(( NOW_EPOCH + 60 ))
-				fire_event '{"type": "ip", "action": "ip_update", "status": "fail"}'
+				fire_event '{"action": "ip_update", "status": "fail"}'
 			else
 				CURRENT_IPV4="$IPV4"
 				CURRENT_IPV6="$IPV6"
@@ -293,13 +293,13 @@ check_ip_status() {
 				bashio::log.info "Dynu IP Updater - All Hosts/Aliases were updated."
 				NOW_EPOCH=$(date +%s)
 				NEXT_CHECK=$(( NOW_EPOCH + (IP_TIME * 60) ))
-				fire_event '{"type": "ip", "action": "ip_update", "status": "success"}'
+				fire_event '{"action": "ip_update", "status": "updated"}'
 			fi
 		else
 			bashio::log.debug "Dynu IP Updater - No IP address change detected."
 			NOW_EPOCH=$(date +%s)
 			NEXT_CHECK=$(( NOW_EPOCH + (IP_TIME * 60) ))
-			fire_event '{"type": "ip", "action": "ip_update", "status": "no_change"}'
+			fire_event '{"action": "ip_update", "status": "no_change"}'
 		fi
 
 	else
@@ -307,7 +307,7 @@ check_ip_status() {
 		bashio::log.error "Dynu IP Updater - Unable to retrieve current IP address data."
 		NOW_EPOCH=$(date +%s)
 		NEXT_CHECK=$(( NOW_EPOCH + 60 ))
-		fire_event '{"type": "ip", "action": "ip_check", "status": "failed"}'
+		fire_event '{"action": "ip_check", "status": "fail"}'
 	fi
 	
 	if [[ "$FIRST_RUN" == "true" ]]; then
