Adding HTTP Status code to Dynu Responses

diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run
@@ -14,6 +14,8 @@ if ! bashio::config.true 'update_cert'; then
 	sleep infinity
 fi
 
+bashio::log.info "Certificate Manager - Started"
+
 DYNU_HOSTNAME=$(bashio::config 'dynu_hostname' | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')
 EMAIL=$(bashio::config 'email' | xargs)
 KEYFILE=$(bashio::config 'keyfile' | xargs)
@@ -45,7 +47,6 @@ fi
 
 CERT_DIR=/data/letsencrypt
 WORK_DIR=/data/workdir
-# DNS_API_KEY=/data/dnsapikey
 DNS_MULTI_CREDS=/data/dns-multi.ini
 ACME_ARGUMENTS=()
 KEY_ARGUMENTS=()
@@ -87,7 +88,7 @@ mqtt_publish() {
     fi
 }
 
-DOMAIN_ARR=()
+DYNU_HOSTNAMES=()
 
 load_api() {
 	# Call Dynu API
@@ -176,52 +177,59 @@ load_api() {
 		return 1
 	fi
 
-	DOMAIN_ARR=()
-
-	for DOMAIN in $CERT_DOMAINS; do
-
-		# Wildcard case
-		if [[ "$DOMAIN" == "*.$DYNU_HOSTNAME" ]]; then
-
-			# Warn if wildcard is not the only entry
-			if [[ "$IP_DOMAINS" != "$DOMAIN" ]]; then
-				bashio::log.warning "Certificate Manager - Wildcard found, ignoring other hostnames"
-			fi
-
-			# Use all hostnames
-			DOMAIN_ARR=(-d "$DOMAIN")
-			break
-		fi
-
-		# Validate domain
-		if [[ ! " ${DYNU_HOSTNAMES[*]} " =~ " $DOMAIN " ]]; then
-			bashio::log.warning "Certificate Manager - $DOMAIN is not valid for this account"
-			continue
-		fi
-
-		DOMAIN_ARR+=(-d "$DOMAIN")
-	done
-
-	if [[ ${#DOMAIN_ARR[@]} -eq 0 ]]; then
-		bashio::log.error "Certificate Manager - no valid hostnames found"
-		return 1
-	fi
-
 	return 0
 }
+
+DYNU_API_CONF="/run/dynu_domain_data.conf"
+DOMAIN_ARR=()
+
+if [[ -f "$DYNU_API_CONF" ]]; then
+	readarray -t DYNU_HOSTNAMES < "$DYNU_API_CONF"
+else
+	if ! load_api; then
+		bashio::log.error "Certificate Manager - Unable to load Dynu API. Check log for details."
+		exit 1
+	fi
+fi
+
+for DOMAIN in $CERT_DOMAINS; do
+	# Wildcard case
+	if [[ "$DOMAIN" == "*.$DYNU_HOSTNAME" ]]; then
+
+		# Warn if wildcard is not the only entry
+		if [[ "$CERT_DOMAINS" != "$DOMAIN" ]]; then
+			bashio::log.warning "Certificate Manager - Wildcard found, ignoring other hostnames"
+		fi
+
+		# Use all hostnames
+		DOMAIN_ARR=(-d "$DOMAIN")
+		break
+	fi
+
+	# Validate domain
+	if [[ ! " ${DYNU_HOSTNAMES[*]} " =~ " $DOMAIN " ]]; then
+		bashio::log.warning "Certificate Manager - $DOMAIN is not valid for this account"
+		continue
+	fi
+
+	DOMAIN_ARR+=(-d "$DOMAIN")
+done
+
+if [[ ${#DOMAIN_ARR[@]} -eq 0 ]]; then
+	bashio::log.error "Certificate Manager - no valid hostnames found"
+	exit 1
+fi
 
 mkdir -p "${WORK_DIR}"
 mkdir -p "${CERT_DIR}"
 
-# touch "${DNS_API_KEY}"
-# chmod 0600 "${DNS_API_KEY}"
 touch "${DNS_MULTI_CREDS}"
 chmod 0600 "${DNS_MULTI_CREDS}"
 
 # Start building the dns-multi credentials file
 echo "# generated by letsencrypt app startup script" > "${DNS_MULTI_CREDS}"
 echo "dns_multi_provider = dynu" >> "${DNS_MULTI_CREDS}"
-echo "DYNU_API_KEY=$(bashio::config 'dynu_api_key')" >> "${DNS_MULTI_CREDS}"
+echo "DYNU_API_KEY=${DYNU_API_KEY}" >> "${DNS_MULTI_CREDS}"
 echo "DYNU_PROPAGATION_TIMEOUT=${PROPAGATION_SECONDS}" >> "${DNS_MULTI_CREDS}"
 
 ACME_ARGUMENTS+=("--authenticator" "dns-multi" "--dns-multi-credentials" "${DNS_MULTI_CREDS}" "--dns-multi-propagation-seconds" "${PROPAGATION_SECONDS}")
@@ -448,10 +456,6 @@ check_cert_dates() {
         fi
     fi
 }
-
-bashio::log.info "Certificate Manager - Started"
-
-load_api
 
 while true; do
 	check_cert_dates
