Applied uniformity to variable bracing

diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/cert-manager/run
@@ -52,8 +52,8 @@ if [[ "$USE_MQTT" == "true" ]]; then
 fi
 
 CERT_DIR=/data/letsencrypt
-CERT_PATH="$CERT_DIR/live/$DYNU_HOSTNAME"
-CERT_FILE="$CERT_PATH/cert.pem"
+CERT_PATH="${CERT_DIR}/live/$DYNU_HOSTNAME"
+CERT_FILE="${CERT_PATH}/cert.pem"
 WORK_DIR=/data/workdir
 DNS_MULTI_CREDS=/data/dns-multi.ini
 ACME_ARGUMENTS=()
@@ -75,12 +75,12 @@ mqtt_publish() {
             -u "$MQTT_USER" \
             -P "$MQTT_PASSWORD" \
 			-i "$MQTT_CLIENT_ID" \
-            -t "dynu_updater/$topic" \
+            -t "dynu_updater/${topic}" \
             -m "$payload" \
             -r \
 			"${TLS_FLAGS[@]}"; then
 
-            bashio::log.warning "Certificate Manager - MQTT publish failed: Topic=$topic."
+            bashio::log.warning "Certificate Manager - MQTT publish failed: Topic=${topic}."
         fi
     fi
 }
@@ -140,11 +140,11 @@ renew_cert() {
 	TMP_OUTPUT=$(mktemp)
 
 	if certbot certonly --non-interactive --keep-until-expiring --expand \
-		  --email "$EMAIL" --agree-tos \
+		  --email "${EMAIL}" --agree-tos \
 		  "${KEY_ARGUMENTS[@]}" \
 		  "${ADDITIONAL_ARGS[@]}" \
-		  --cert-name "$DYNU_HOSTNAME" "${DOMAIN_ARR[@]/#/-d }" \
-		  --config-dir "$CERT_DIR" --work-dir "$WORK_DIR" \
+		  --cert-name "${DYNU_HOSTNAME}" "${DOMAIN_ARR[@]/#/-d }" \
+		  --config-dir "${CERT_DIR}" --work-dir "${WORK_DIR}" \
 		  --preferred-challenges dns \
 		  "${ACME_ARGUMENTS[@]}" \
 		  2>&1 | tee "$TMP_OUTPUT"; then
@@ -155,7 +155,7 @@ renew_cert() {
 	
 	# If certbot failed
 	if [[ "$CERTBOT_EXIT" -ne 0 ]]; then
-		bashio::log.error "Certificate Manager - Certbot failed with code $CERTBOT_EXIT."
+		bashio::log.error "Certificate Manager - Certbot failed with code ${CERTBOT_EXIT}."
 		LAST_CHECK="error"
 	else
 		# If certbot succeeded, check if certificate was updated
@@ -193,42 +193,39 @@ check_cert_dates() {
     elif [[ -f "$CERT_FILE" ]]; then
 		bashio::log.info "Certificate Manager - Checking certificate dates."
 		mqtt_publish "last_cert_check" "$(date -Is)"
-        if ! VALID_FROM_RAW=$(openssl x509 -in "$CERT_FILE" -noout -startdate 2>/dev/null | cut -d= -f2); then
+        if ! VALID_FROM_RAW=$(openssl x509 -in "${CERT_FILE}" -noout -startdate 2>/dev/null | cut -d= -f2); then
 			VALID_FROM_RAW=""
 		fi
-		if ! CREATED_RAW=$(stat -c %y "$CERT_FILE"); then
+		if ! CREATED_RAW=$(stat -c %y "${CERT_FILE}"); then
 			CREATED_RAW=""
 		fi
-		if ! EXPIRY_RAW=$(openssl x509 -in "$CERT_FILE" -noout -enddate 2>/dev/null | cut -d= -f2); then
+		if ! EXPIRY_RAW=$(openssl x509 -in "${CERT_FILE}" -noout -enddate 2>/dev/null | cut -d= -f2); then
 			EXPIRY_RAW=""
 		fi
-
-		bashio::log.warning "Created RAW: $CREATED_RAW"
-		bashio::log.warning "Expiry RAW: $EXPIRY_RAW"
 		
         # If parsing fails, force renewal
         if [[ -n "$VALID_FROM_RAW" && -n "$CREATED_RAW" && -n "$EXPIRY_RAW" ]]; then
-			VALID_FROM_ISO=$(date -u -d "$VALID_FROM_RAW" +"%Y-%m-%dT%H:%M:%S+00:00")
-			CREATED_ISO=$(date -u -d "$CREATED_RAW" +"%Y-%m-%dT%H:%M:%S+00:00")
-			EXPIRY_ISO=$(date -u -d "$EXPIRY_RAW" +"%Y-%m-%dT%H:%M:%S+00:00")
+			VALID_FROM_ISO=$(date -u -d "${VALID_FROM_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
+			CREATED_ISO=$(date -u -d "${CREATED_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
+			EXPIRY_ISO=$(date -u -d "${EXPIRY_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
 
             mqtt_publish "cert_expires" "$EXPIRY_ISO"
             mqtt_publish "cert_created" "$CREATED_ISO"
 
-            EXPIRY_EPOCH=$(date -d "$EXPIRY_RAW" +%s)
+            EXPIRY_EPOCH=$(date -d "${EXPIRY_RAW}" +%s)
             NOW_EPOCH=$(date +%s)
             MAX_EPOCH=$(( NOW_EPOCH + (CHECK_DAYS * 86400) + 60 ))
 			
-			bashio::log.info "Certificate Manager - Certificate created $CREATED_ISO."
-			bashio::log.info "Certificate Manager - Certificate valid from $VALID_FROM_ISO."
-			bashio::log.info "Certificate Manager - Certificate expires $EXPIRY_ISO."
+			bashio::log.info "Certificate Manager - Certificate created ${CREATED_ISO}."
+			bashio::log.info "Certificate Manager - Certificate valid from ${VALID_FROM_ISO}."
+			bashio::log.info "Certificate Manager - Certificate expires ${EXPIRY_ISO}."
 			
             if (( EXPIRY_EPOCH < NOW_EPOCH )); then
                 bashio::log.info "Certificate Manager - Certificate expired, renewing."
 				mqtt_publish "last_cert_status" "false"
                 renew_cert
             elif (( EXPIRY_EPOCH <= MAX_EPOCH )); then
-				bashio::log.info "Certificate Manager - Certificate expires in less than $CHECK_DAYS days, renewing."
+				bashio::log.info "Certificate Manager - Certificate expires in less than ${CHECK_DAYS} days, renewing."
                 mqtt_publish "last_cert_status" "true"
                 renew_cert
             else
@@ -257,25 +254,25 @@ check_cert_dates() {
 			bashio::log.warning "Certificate Manager - Last renewal failed. Retrying in 10 minutes."
 			LOOP_SLEEP=600
 		elif [[ -f "$CERT_FILE" ]]; then
-			if ! VALID_FROM_RAW=$(openssl x509 -in "$CERT_FILE" -noout -startdate 2>/dev/null | cut -d= -f2); then
+			if ! VALID_FROM_RAW=$(openssl x509 -in "${CERT_FILE}" -noout -startdate 2>/dev/null | cut -d= -f2); then
 				VALID_FROM_RAW=""
 			fi
-			if ! CREATED_RAW=$(stat -c %y "$CERT_FILE"); then
+			if ! CREATED_RAW=$(stat -c %y "${CERT_FILE}"); then
 				CREATED_RAW=""
 			fi
-			if ! EXPIRY_RAW=$(openssl x509 -in "$CERT_FILE" -noout -enddate 2>/dev/null | cut -d= -f2); then
+			if ! EXPIRY_RAW=$(openssl x509 -in "${CERT_FILE}" -noout -enddate 2>/dev/null | cut -d= -f2); then
 				EXPIRY_RAW=""
 			fi
 
             if [[ -n "$VALID_FROM_RAW" && -n "$CREATED_RAW" && -n "$EXPIRY_RAW" ]]; then
-				VALID_FROM_ISO=$(date -u -d "$VALID_FROM_RAW" +"%Y-%m-%dT%H:%M:%S+00:00")
-				CREATED_ISO=$(date -u -d "$CREATED_RAW" +"%Y-%m-%dT%H:%M:%S+00:00")
-				EXPIRY_ISO=$(date -u -d "$EXPIRY_RAW" +"%Y-%m-%dT%H:%M:%S+00:00")
+				VALID_FROM_ISO=$(date -u -d "${VALID_FROM_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
+				CREATED_ISO=$(date -u -d "${CREATED_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
+				EXPIRY_ISO=$(date -u -d "${EXPIRY_RAW}" +"%Y-%m-%dT%H:%M:%S+00:00")
 
 				mqtt_publish "cert_expires" "$EXPIRY_ISO"
 				mqtt_publish "cert_created" "$CREATED_ISO"
 
-                EXPIRY_EPOCH=$(date -d "$EXPIRY_RAW" +%s)
+                EXPIRY_EPOCH=$(date -d "${EXPIRY_RAW}" +%s)
                 NOW_EPOCH=$(date +%s)
 
                 if (( EXPIRY_EPOCH < NOW_EPOCH )); then
@@ -306,7 +303,7 @@ while true; do
 	check_cert_dates
 	
 	NEXT_RUN_ISO=$(date -Is -d "@$(( $(date +%s) + LOOP_SLEEP ))")
-	bashio::log.info "Certificate Manager - Next renewal check: $NEXT_RUN_ISO."
+	bashio::log.info "Certificate Manager - Next renewal check: ${NEXT_RUN_ISO}."
 	mqtt_publish "next_cert_check" "$NEXT_RUN_ISO"
 	
 	sleep "$LOOP_SLEEP"
diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
@@ -166,7 +166,7 @@ fi
 
 bashio::log.info "Dynu Updater Initialisation - Contacting Dynu API."
 
-if DYNU_API_RESPONSE=$(curl -s --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.dynu.com/v2/dns" 2>/dev/null); then
+if DYNU_API_RESPONSE=$(curl -s --max-time 5 -H "API-Key: ${DYNU_API_KEY}" "https://api.dynu.com/v2/dns" 2>/dev/null); then
 	HTTP_STATUS=$(jq -r '.statusCode // empty' <<< "$DYNU_API_RESPONSE")
 	
 	if [[ -z "$HTTP_STATUS" ]]; then
@@ -183,7 +183,7 @@ if DYNU_API_RESPONSE=$(curl -s --max-time 5 -H "API-Key: $DYNU_API_KEY" "https:/
 			bashio::log.info "Dynu Updater Initialisation - Dynu Domain API data retrieved."
 			;;
 		*)
-			bashio::log.error "Dynu Updater Initialisation - Dynu Domain API Error: status: $HTTP_STATUS, type: $EXCEPTION_TYPE, message: $EXCEPTION_MESSAGE."
+			bashio::log.error "Dynu Updater Initialisation - Dynu Domain API Error: status: ${HTTP_STATUS}, type: ${EXCEPTION_TYPE}, message: ${EXCEPTION_MESSAGE}."
 			exit 1
 			;;
 
@@ -195,7 +195,7 @@ fi
 
 # Retrieve Domain ID
 DYNU_DOMAIN_ID=$(
-	jq -r --arg HOST "$DYNU_HOSTNAME" '
+	jq -r --arg HOST "${DYNU_HOSTNAME}" '
 		.domains[]
 		| select(.name == $HOST)
 		| .id // empty
@@ -207,7 +207,7 @@ if [[ -z "$DYNU_DOMAIN_ID" ]]; then
 fi
 
 # Retrieve IPv6 enabled status for domain
-DYNU_IPV6_ENABLED=$(jq -r --arg HOST "$DYNU_HOSTNAME" '
+DYNU_IPV6_ENABLED=$(jq -r --arg HOST "${DYNU_HOSTNAME}" '
 	.domains[]
 	| select(.name == $HOST)
 	| .ipv6 // "false"
@@ -217,7 +217,7 @@ if [[ "$DYNU_IPV6_ENABLED" == "true" ]]; then
 	bashio::log.info "Dynu Updater Initialisation - IPv6 enabled for $DYNU_HOSTNAME."
 fi
 
-if DYNU_RECORDS=$(curl -s --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.dynu.com/v2/dns/${DYNU_DOMAIN_ID}/record" 2>/dev/null); then
+if DYNU_RECORDS=$(curl -s --max-time 5 -H "API-Key: ${DYNU_API_KEY}" "https://api.dynu.com/v2/dns/${DYNU_DOMAIN_ID}/record" 2>/dev/null); then
 	HTTP_STATUS=$(jq -r '.statusCode // empty' <<< "$DYNU_RECORDS")
 	
 	if [[ -z "$HTTP_STATUS" ]]; then
@@ -236,7 +236,7 @@ if DYNU_RECORDS=$(curl -s --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.
 			bashio::log.info "Dynu Updater Initialisation - Dynu Records API data retrieved."
 			;;
 		*)
-			bashio::log.error "Dynu Updater Initialisation - Dynu Records API Error: status: $HTTP_STATUS, type: $EXCEPTION_TYPE, message: $EXCEPTION_MESSAGE."
+			bashio::log.error "Dynu Updater Initialisation - Dynu Records API Error: status: ${HTTP_STATUS}, type: ${EXCEPTION_TYPE}, message: ${EXCEPTION_MESSAGE}."
 			exit 1
 			;;
 
@@ -269,7 +269,7 @@ CERT_HOSTNAMES=()
 if [[ "$DNS_VALID" == "true" ]]; then
 	for DOMAIN in $IP_DOMAINS; do
 		if [[ "$DOMAIN" != "*.$DYNU_HOSTNAME" && ! " ${DYNU_HOSTNAMES[*]} " =~ " $DOMAIN " ]]; then
-			bashio::log.error "Dynu Updater Initialisation - DNS Update Hostname $DOMAIN is not valid for this account."
+			bashio::log.error "Dynu Updater Initialisation - DNS Update Hostname ${DOMAIN} is not valid for this account."
 			exit 1
 		elif [[ "$DOMAIN" == "*.$DYNU_HOSTNAME" ]]; then
 			# Warn if wildcard is not the only entry
@@ -291,7 +291,7 @@ fi
 if [[ "$CERT_VALID" == "true" ]]; then
 	for DOMAIN in $CERT_DOMAINS; do
 		if [[ "$DOMAIN" != "*.$DYNU_HOSTNAME" && ! " ${DYNU_HOSTNAMES[*]} " =~ " $DOMAIN " ]]; then
-			bashio::log.error "Dynu Updater Initialisation - Certificate Hostname $DOMAIN is not valid for this account."
+			bashio::log.error "Dynu Updater Initialisation - Certificate Hostname ${DOMAIN} is not valid for this account."
 			exit 1
 		elif [[ "$DOMAIN" == "*.$DYNU_HOSTNAME" ]]; then
 			# Warn if wildcard is not the only entry
@@ -396,26 +396,26 @@ if [[ "$USE_MQTT" == "true" ]]; then
 		fi
 	fi
 	
-	bashio::log.info "Dynu Updater Initialisation - Testing MQTT connection to $MQTT_HOST."
+	bashio::log.info "Dynu Updater Initialisation - Testing MQTT connection to ${MQTT_HOST}."
 	TEST_TOPIC="dynu_updater/selftest"
     TEST_PAYLOAD="selftest_$(date +%s)"
 	
-	if ! timeout 2 bash -c "echo > /dev/tcp/$MQTT_HOST/$MQTT_PORT" 2>/dev/null; then
-		bashio::log.error "Dynu Updater Initialisation - Cannot reach MQTT Server at $MQTT_HOST:$MQTT_PORT."
+	if ! timeout 2 bash -c "echo > /dev/tcp/${MQTT_HOST}/${MQTT_PORT}" 2>/dev/null; then
+		bashio::log.error "Dynu Updater Initialisation - Cannot reach MQTT Server at ${MQTT_HOST}:${MQTT_PORT}."
 		exit 1
 	elif ! OUTPUT=$(mosquitto_pub \
-		-h "$MQTT_HOST" \
-		-u "$MQTT_USER" \
-		-P "$MQTT_PASSWORD" \
+		-h "${MQTT_HOST}" \
+		-u "${MQTT_USER}" \
+		-P "${MQTT_PASSWORD}" \
 		-i "$(hostname)" \
-		-p "$MQTT_PORT" \
-		-t "$TEST_TOPIC" \
-		-m "$TEST_PAYLOAD" \
+		-p "${MQTT_PORT}" \
+		-t "${TEST_TOPIC}" \
+		-m "${TEST_PAYLOAD}" \
 		-q 1 \
 		"${TLS_FLAGS[@]}" \
 		2>&1); then
 		
-		bashio::log.error "Dynu Updater Initialisation - Unable to connect to $MQTT_HOST: $OUTPUT."
+		bashio::log.error "Dynu Updater Initialisation - Unable to connect to ${MQTT_HOST}: ${OUTPUT}."
 		if [[ "$MQTT_USE_TLS" == "true" ]]; then
 			bashio::log.info "Dynu Updater Initialisation - Checking OpenSSL Connection."
 			if ! TLS_OUTPUT=$(openssl s_client -connect "${MQTT_HOST}:${MQTT_PORT}" \
@@ -423,15 +423,15 @@ if [[ "$USE_MQTT" == "true" ]]; then
 				"${OPENSSL_FLAGS[@]}" \
 				-verify 10 -verify_return_error < /dev/null 2>&1); then
 				
-				REASON=$(echo "$TLS_OUTPUT" | grep -E "verify error|Verify return code|Hostname mismatch|expired|unable|self signed" | head -n 1)
-				bashio::log.error "Dynu Updater Initialisation - OpenSSL query returned: $REASON."
+				REASON=$(echo "${TLS_OUTPUT}" | grep -E "verify error|Verify return code|Hostname mismatch|expired|unable|self signed" | head -n 1)
+				bashio::log.error "Dynu Updater Initialisation - OpenSSL query returned: ${REASON}."
 			else
 				bashio::log.error "Dynu Updater Initialisation - OpenSSL query returned: Success."
 			fi
 		fi
 		exit 1
 	else
-		bashio::log.info "Dynu Updater Initialisation - Connected to $MQTT_HOST."	
+		bashio::log.info "Dynu Updater Initialisation - Connected to ${MQTT_HOST}."	
 	fi
 
 	MQTT_ENTITIES=(
@@ -449,7 +449,7 @@ if [[ "$USE_MQTT" == "true" ]]; then
 	)
 
 	# MQTT Device metadata
-	DEVICE_ID="dynu_updater_$(hostname)"
+	DEVICE_ID="dynu_updater_$hostname"
 	DEVICE_NAME="Dynu Updater"
 	MANUFACTURER="TheUkShadow"
 	MODEL="Dynu Updater Companion Integration"
@@ -508,7 +508,7 @@ if [[ "$USE_MQTT" == "true" ]]; then
 				  }" \
 				  "${TLS_FLAGS[@]}"; then
 				
-				bashio::log.warning "Dynu Updater Initialisation - MQTT discovery failed for entity $entity_id."
+				bashio::log.warning "Dynu Updater Initialisation - MQTT discovery failed for entity ${entity_id}."
 			fi	
 		fi
 	}
@@ -524,12 +524,12 @@ if [[ "$USE_MQTT" == "true" ]]; then
 				-u "$MQTT_USER" \
 				-P "$MQTT_PASSWORD" \
 				-i "$(hostname)" \
-				-t "dynu_updater/$topic" \
+				-t "dynu_updater/${topic}" \
 				-m "$payload" \
 				-r \
 				"${TLS_FLAGS[@]}"; then
 
-				bashio::log.warning "Dynu Updater Initialisation - MQTT publish failed for topic $topic."
+				bashio::log.warning "Dynu Updater Initialisation - MQTT publish failed for topic ${topic}."
 			fi
 		fi
 	}
