Refactoring scripts

diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
@@ -5,32 +5,31 @@
 # DNS Updater
 # ==============================================================================
 
-if bashio::config.has_value 'dynu_hostname'; then
-	DYNU_HOSTNAME=$(bashio::config 'dynu_hostname' | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')
-else
-	DYNU_HOSTNAME=""
-fi
-if bashio::config.has_value 'dynu_update_password'; then
-	PASSWORD=$(bashio::config 'dynu_update_password' | xargs)
-else
-	PASSWORD=""
-fi
+DYNU_HOSTNAME=$(bashio::config 'dynu_hostname' | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')
+PASSWORD=$(bashio::config 'dynu_update_password' | xargs)
+IP_DOMAINS=$(bashio::config 'ip_domains' | tr '[:upper:]' '[:lower:]' | xargs)
+DYNU_API_KEY=$(bashio::config 'dynu_api_key' | xargs)
+
 if bashio::config.true 'verbose'; then
     VERBOSE="true"
 else
     VERBOSE="false"
 fi
+if bashio::config.true 'mqtt'; then
+    USE_MQTT="true"
+else
+    USE_MQTT="false"
+fi
 
 MQTT_CONF="/run/dynu-mqtt.conf"
 
-if [[ -f "$MQTT_CONF" ]]; then
+if [[ "$USE_MQTT" == "true" && -f "$MQTT_CONF" ]]; then
 	USE_MQTT=$(jq -r '.mqtt' "$MQTT_CONF")
 	MQTT_HOST=$(jq -r '.host' "$MQTT_CONF")
 	MQTT_PORT=$(jq -r '.port' "$MQTT_CONF")
 	MQTT_USER=$(jq -r '.user' "$MQTT_CONF")
 	MQTT_PASSWORD=$(jq -r '.password' "$MQTT_CONF")
 else
-	bashio::log.error "Dynu DNS Updater - MQTT config not found"
 	USE_MQTT="false"
 fi
 	
@@ -52,6 +51,50 @@ mqtt_publish() {
         fi
     fi
 }
+
+# Call Dynu API
+if ! DYNU_API_RESPONSE=$(curl -s --fail --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.dynu.com/v2/dns" 2>/dev/null); then
+	bashio::log.error "Dynu DNS Updater - unable to contact Dynu API (network error or invalid API key)"
+    sleep 1
+	exit 1
+fi
+
+bashio::log.info "$DYNU_API_RESPONSE"
+
+DYNU_DOMAIN_ID=$(echo "$DYNU_API_RESPONSE" \
+	| jq -r --arg HOST "$DYNU_HOSTNAME" '
+		.dnsRecords[] | select(.name == $HOST) | .id // empty
+	')
+
+if [[ -z "$DYNU_DOMAIN_ID" ]]; then
+	bashio::log.error "Dynu DNS Updater - '$DYNU_HOSTNAME' not found in Dynu domain list"
+	sleep 1
+	exit 1
+fi
+
+if ! DYNU_RECORDS=$(curl -s --fail --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.dynu.com/v2/dns/${DYNU_DOMAIN_ID}/record" 2>/dev/null); then
+	bashio::log.error "Dynu DNS Updater - failed to retrieve valid DNS records from Dynu API"
+	sleep 1
+	exit 1
+fi
+
+DYNU_IPV6_ENABLED=$(
+	echo "$DYNU_API_RESPONSE" \
+	| jq -r --arg HOST "$DYNU_HOSTNAME" '
+		.dnsRecords[]
+		| select(.name == $HOST)
+		| .ipv6
+	'
+)
+
+DYNU_HOSTNAMES=$(
+  jq -r '
+    [.dnsRecords[].hostname]
+    | unique
+    | sort_by( (split(".") | length), . )
+    | .[]
+  ' <<< "$DYNU_RECORDS"
+)
 
 STATE_FILE="/run/dynu-dns.conf"
 
