Updated config file detection

diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
@@ -13,16 +13,12 @@ fi
 
 DYNU_CONF="/run/dynu-updater.conf"
 
-WAIT_COUNT=0
-while [[ ! -f "$DYNU_CONF" ]]; do
-	bashio::log.info "Dynu DNS Updater - Conf file not found"
-	WAIT_COUNT=$((WAIT_COUNT + 1))
-	if (( WAIT_COUNT > 20 )); then
-		bashio::log.error "Dynu DNS Updater - Dynu API Config not found"
-		exit 1
-	fi
-	sleep 1
-done
+sleep 1
+
+if [[ ! -f "$DYNU_CONF" ]]; then
+	bashio::log.error "Dynu DNS Updater - Dynu API Config not found"
+	exit 1
+fi
 
 bashio::log.info "Dynu DNS Updater - Started"
 
