Adding HTTP Status code to Dynu Responses

diff --git a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
--- a/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
+++ b/dynu_updater/rootfs/etc/s6-overlay/s6-rc.d/dns-update/run
@@ -83,35 +83,34 @@ load_api() {
 	# Call Dynu API
 	bashio::log.info "Dynu DNS Updater - Loading data from Dynu API"
 	
-	if DYNU_API_RESPONSE=$(curl -s --max-time 5 -H "API-Key: $DYNU_API_KEY" -w "\n%{http_code}" "https://api.dynu.com/v2/dns" 2>/dev/null); then
-		
-		bashio::log.warning "API Response: $DYNU_API_RESPONSE"
-		
-		HTTP_STATUS=$(tail -n1 <<< "$DYNU_API_RESPONSE")
-		# Handle HTTP status codes explicitly
+	if DYNU_API_RESPONSE=$(curl -s --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.dynu.com/v2/dns" 2>/dev/null); then
+		HTTP_STATUS=$(
+		jq -r --arg HOST "$DYNU_HOSTNAME" '
+			.statusCode // empty
+		' <<< "$DYNU_API_RESPONSE")
+
 		case "$HTTP_STATUS" in
 			200)
-				DYNU_API_RESPONSE=$(sed '$d' <<< "$DYNU_API_RESPONSE")
+				bashio::log.info "Dynu DNS Updater - Dynu Domain API data retrieved."
 				;;
 			401)
 				bashio::log.error "Dynu Updater Initialisation - Invalid Dynu API key"
 				exit 1
 				;;
 			403)
-				bashio::log.error "Dynu Updater Initialisation - Dynu API key does not have permission to access DNS records"
+				bashio::log.error "Dynu Updater Initialisation - Dynu Domain API key does not have permission to access DNS records"
 				exit 1
 				;;
 			*)
-				bashio::log.error "Dynu Updater Initialisation - Dynu API returned HTTP $HTTP_STATUS"
+				bashio::log.error "Dynu Updater Initialisation - Dynu Domain API returned HTTP $HTTP_STATUS"
 				exit 1
 				;;
 		esac
 	else
-		bashio::log.error "Dynu Updater Initialisation - Dynu API returned HTTP $HTTP_STATUS"
+		bashio::log.error "Dynu Updater Initialisation - Dynu Domain API could not be loaded"
 		exit 1
 	fi
-
-
+	
 	# Retrieve Domain ID
 	DYNU_DOMAIN_ID=$(
 		jq -r --arg HOST "$DYNU_HOSTNAME" '
@@ -124,18 +123,41 @@ load_api() {
 		bashio::log.error "Dynu DNS Updater - '$DYNU_HOSTNAME' not found in Dynu domain list"
 		return 1
 	fi
-
-	# Retrieve DNS Records for Domain
-	if ! DYNU_RECORDS=$(curl -s --fail --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.dynu.com/v2/dns/${DYNU_DOMAIN_ID}/record" 2>/dev/null); then
-		bashio::log.error "Dynu DNS Updater - failed to retrieve valid DNS records from Dynu API"
-		return 1
-	fi
-
+	
+	# Retrieve IPv6 enabled status for domain
 	DYNU_IPV6_ENABLED=$(jq -r --arg HOST "$DYNU_HOSTNAME" '
 		.domains[]
 		| select(.name == $HOST)
 		| .ipv6 // "false"
 	' <<<"$DYNU_API_RESPONSE")
+
+	if DYNU_RECORDS=$(curl -s --max-time 5 -H "API-Key: $DYNU_API_KEY" "https://api.dynu.com/v2/dns/${DYNU_DOMAIN_ID}/record" 2>/dev/null); then
+		HTTP_STATUS=$(
+		jq -r --arg HOST "$DYNU_HOSTNAME" '
+			.statusCode // empty
+		' <<< "$DYNU_RECORDS")
+
+		case "$HTTP_STATUS" in
+			200)
+				bashio::log.info "Dynu DNS Updater - Dynu Records API data retrieved."
+				;;
+			401)
+				bashio::log.error "Dynu Updater Initialisation - Invalid Dynu API key"
+				exit 1
+				;;
+			403)
+				bashio::log.error "Dynu Updater Initialisation - Dynu API key does not have permission to access DNS records"
+				exit 1
+				;;
+			*)
+				bashio::log.error "Dynu Updater Initialisation - Dynu Records API returned HTTP $HTTP_STATUS"
+				exit 1
+				;;
+		esac
+	else
+		bashio::log.error "Dynu Updater Initialisation - Dynu Records API could not be loaded"
+		exit 1
+	fi
 
 	DYNU_HOSTNAMES=$(
 	  jq -r '
@@ -148,6 +170,8 @@ load_api() {
 		| .[]
 	  ' <<< "$DYNU_RECORDS"
 	)
+	
+	bashio::log.warning "Dynu Hosts: $DYNU_HOSTNAMES"
 
 	DOMAIN_ARR=()
 	for DOMAIN in $IP_DOMAINS; do
