Added options for Timing and tweaked sleep code

diff --git a/dynu-updater/rootfs/etc/s6-overlay/s6-rc.d/init/run b/dynu-updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
--- a/dynu-updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
+++ b/dynu-updater/rootfs/etc/s6-overlay/s6-rc.d/init/run
@@ -22,6 +22,8 @@ DYNU_API_KEY=$(bashio::config 'dynu_api_key' | xargs)
 PASSWORD=$(bashio::config 'dynu_update_password' | xargs)
 KEYFILE=$(bashio::config 'keyfile' | xargs)
 CERTFILE=$(bashio::config 'certfile' | xargs)
+CERT_TIME=$(bashio::config 'update_cert_time' | xargs)
+IP_FREQ=$(bashio::config 'update_ip_freq')
 CERT_VALID=$(bashio::config 'update_cert')
 DNS_VALID=$(bashio::config 'update_ip')
 
@@ -34,7 +36,7 @@ if [[ "$CERT_VALID" == "false" && "$DNS_VALID" == "false" ]]; then
     exit 1
 fi
 
-if [[ -z "$HOSTNAME" || ! "$HOSTNAME" =~ ^[A-Za-z0-9.-]+\.[A-Za-z]{2,}(?:\.[A-Za-z]{2,})*$ ]]; then
+if [[ -z "$HOSTNAME" || ! "$HOSTNAME" =~ ^[A-Za-z0-9.-]+\.[A-Za-z]{2,}(\.[A-Za-z]{2,})*$ ]]; then
     bashio::log.error "Dynu Updater Initialisation - Invalid Dynu Hostname"
     exit 1
 fi
@@ -44,41 +46,56 @@ if [[ -z "$DYNU_API_KEY" ]]; then
     exit 1
 fi
 
-if [[ -z "$EMAIL" || ! "$EMAIL" =~ ^[^@]+@[^@]+\.[^@]+$ ]]; then
-    bashio::log.info "Dynu Updater Initialisation - invalid email address"
-	CERT_VALID="false"
+if [[ "$CERT_VALID" == "true" ]]; then
+	if [[ -z "$EMAIL" || ! "$EMAIL" =~ ^[^@]+@[^@]+\.[^@]+$ ]]; then
+		bashio::log.info "Dynu Updater Initialisation - invalid email address"
+		CERT_VALID="false"
+	fi
+
+	if [[ -z "$CERT_DOMAINS" ]]; then
+		bashio::log.info "Dynu Updater Initialisation - no Certificate Hostnames configured"
+		CERT_VALID="false"
+	fi
+
+	if [[ -z "$CERTFILE" || ! "$CERTFILE" =~ ^[A-Za-z0-9._/-]+$ ]]; then
+		bashio::log.info "Dynu Updater Initialisation - Invalid Certificate File"
+		CERT_VALID="false"
+	fi
+
+	if [[ -z "$KEYFILE" || ! "$KEYFILE" =~ ^[A-Za-z0-9._/-]+$ ]]; then
+		bashio::log.info "Dynu Updater Initialisation - Invalid Private Key File"
+		CERT_VALID="false"
+	fi
+	
+	if [[ -z "$CERT_TIME" || ! "$CERT_TIME" =~ ^([01][0-9]|2[0-3]):[0-5][0-9]$ ]]; then
+		bashio::log.info "Dynu Updater Initialisation - Invalid Certificate Check Time (00:00 - 23:59)"
+		CERT_VALID="false"
+	fi
 fi
 
-if [[ -z "$CERT_DOMAINS" ]]; then
-    bashio::log.info "Dynu Updater Initialisation - no Certificate Hostnames configured"
-	CERT_VALID="false"
-fi
+if [[ "$DNS_VALID" == "true" ]]; then
+	if [[ -z "$IP_DOMAINS" ]]; then
+		bashio::log.info "Dynu Updater Initialisation - no DNS Update Hostnames configured"
+		DNS_VALID="false"
+	fi
 
-if [[ -z "$CERTFILE" || ! "$CERTFILE" =~ ^[A-Za-z0-9._/-]+$ ]]; then
-	bashio::log.info "Dynu Updater Initialisation - Invalid Certificate File"
-	CERT_VALID="false"
-fi
-
-if [[ -z "$KEYFILE" || ! "$KEYFILE" =~ ^[A-Za-z0-9._/-]+$ ]]; then
-	bashio::log.info "Dynu Updater Initialisation - Invalid Private Key File"
-	CERT_VALID="false"
-fi
-
-if [[ -z "$IP_DOMAINS" ]]; then
-    bashio::log.info "Dynu Updater Initialisation - no DNS Update Hostnames configured"
-	DNS_VALID="false"
-fi
-
-if [[ -z "$PASSWORD" ]]; then
-    bashio::log.info "Dynu Updater Initialisation - no Dynu Account Password configured"
-	DNS_VALID="false"
+	if [[ -z "$PASSWORD" ]]; then
+		bashio::log.info "Dynu Updater Initialisation - no Dynu Account Password configured"
+		DNS_VALID="false"
+	fi
+	if [[ -z "$IP_FREQ" || ! "$IP_FREQ" =~ ^[0-9]+$ ]] || (( IP_FREQ < 60 || IP_FREQ > 3600 )); then
+		bashio::log.info "Dynu Updater Initialisation - Invalid IP Update Frequency (60 - 3600)"
+		DNS_VALID="false"
+	else
+		
+	fi
 fi
 
 if [[ "$DNS_VALID" == "false" ]] && [[ "$CERT_VALID" == "false" ]]; then
 	bashio::log.error "Dynu Updater Initialisation - No valid configuration for Certificate generation or DNS IP Updates"
-    exit 1
+	exit 1
 fi
-
+	
 # Call Dynu API: capture JSON body AND HTTP status separately
 DYNU_API_RESPONSE=$(curl -s --fail --max-time 5 \
     -H "API-Key: $DYNU_API_KEY" \
